#!/usr/bin/env python3
"""Mechanical C99 transcription of the OpenGV GP3P Groebner-basis solver (external/vio/okvis2/external/opengv/src/absolute_pose/
modules/gp3p/{init,code,reductors,spolynomials}.cpp, BSD-3-Clause, Copyright (c) 2013 Laurent Kneip, ANU) into
okvis_port/c/ok_opengv_gp3p_gen.c. Only the Eigen element / row accessors are rewritten; every arithmetic expression is kept
verbatim (row operations are element-wise, so their evaluation order is the C order). Run from the repo root."""
import re, sys
from pathlib import Path

SRC = Path("external/vio/okvis2/external/opengv/src/absolute_pose/modules/gp3p")
OUT = Path("okvis_port/c/ok_opengv_gp3p_gen.c")
LICENSE = (SRC / "init.cpp").read_text().split("*/")[0] + "*/"


def conv_body(body):
    out = []
    for line in body.split("\n"):
        m = re.match(r"^(\s*)groebnerMatrix\.row\((\d+)\) = factor \* groebnerMatrix\.row\((\d+)\);\s*$", line)
        if m:
            i, a, b = m.groups()
            assert a == b
            out.append(f"{i}for (c = 0; c < 85; ++c) G({a},c) = factor * G({a},c);")
            continue
        m = re.match(r"^(\s*)groebnerMatrix\.row\((\d+)\) = groebnerMatrix\.row\((\d+)\) - factor \* groebnerMatrix\.row\((\d+)\);\s*$", line)
        if m:
            i, a, b, d = m.groups()
            assert a == b
            out.append(f"{i}for (c = 0; c < 85; ++c) G({a},c) = G({a},c) - factor * G({d},c);")
            continue
        assert "row(" not in line, line
        line = re.sub(r"groebnerMatrix\(([^,()]+),([^()]+)\)", r"G(\1,\2)", line)
        line = re.sub(r"\b([fvp])\((\d),(\d)\)", lambda mm: mm.group(1).upper() + f"({mm.group(2)},{mm.group(3)})", line)
        line = line.replace("groebnerMatrix", "groebner")
        out.append(line)
    return "\n".join(out)


funcs = []
for name in ("init", "code", "reductors", "spolynomials"):
    text = (SRC / f"{name}.cpp").read_text()
    for m in re.finditer(r"void\s*\n(?:opengv::absolute_pose::modules::gp3p::)(\w+)\(\s*([^)]*?)\s*\)\s*\n\{\n(.*?)\n\}\n", text, re.S):
        fn, params, body = m.group(1), m.group(2), m.group(3)
        body = conv_body(body)
        if fn == "init":
            sig = "void ok_og_gp3p_init(double* groebner, const double* f, const double* v, const double* p)"
            body = "    (void)f; (void)v; (void)p;\n" + body
        elif fn == "compute":
            sig = "void ok_og_gp3p_compute(double* groebner)"
        elif fn.startswith("groebnerRow"):
            sig = f"static void {fn}(double* groebner, int targetRow)"
        else:
            sig = f"static void {fn}(double* groebner)"
        uses_c = "c)" in body or "c," in body and "for (c" in body
        decl = "    int c; (void)c;\n" if "for (c" in body else ""
        funcs.append((fn, sig, decl + body))

assert funcs[0][0] == "init"
ordered = [f for f in funcs if f[0] not in ("init", "compute")] + [f for f in funcs if f[0] in ("init", "compute")]
res = [LICENSE, "",
       "/* Generated by tools/gen_okvis_gp3p.py from the OpenGV gp3p module (BSD-3-Clause, see okvis_port/LICENSES/opengv-BSD-3-Clause.txt);",
       " * do not edit. G(r,c) = row-major 48 x 85 Groebner matrix; F / V / P(i,j) = column-major 3 x 3 (Eigen layout). */",
       "#include <math.h>", '#include "ok_opengv.h"', "#define G(r,c) (groebner[(r) * 85 + (c)])",
       "#define F(i,j) (f[(i) + 3 * (j)])", "#define V(i,j) (v[(i) + 3 * (j)])", "#define P(i,j) (p[(i) + 3 * (j)])", ""]
# groebnerRow* take (G,row): the macro G needs the pointer named groebner
for fn, sig, body in ordered:
    res += [sig, "{", body, "}", ""]
Path(OUT).write_text("\n".join(res).replace("double factor = ", "double factor = ").replace("\n\n\n", "\n\n"))
print("wrote", OUT, len(funcs), "functions")
