#!/usr/bin/env python3
"""Mechanical C99 transcription of OpenGV's Stewenius 5-point polynomial composition (external/vio/okvis2/external/opengv/src/
relative_pose/modules/fivept_stewenius/modules.cpp, BSD-3-Clause, Copyright (c) 2013 Laurent Kneip, ANU) into
okvis_port/c/ok_opengv_stew_gen.c. Only the Eigen accessors EE(i,j) / A(i,j) are rewritten; every expression is kept verbatim
(left-to-right products and sums, int * double literals as written). Run from the repo root."""
import re
from pathlib import Path

SRC = Path("external/vio/okvis2/external/opengv/src/relative_pose/modules/fivept_stewenius/modules.cpp")
OUT = Path("okvis_port/c/ok_opengv_stew_gen.c")
text = SRC.read_text()
license_ = text.split("*/")[0] + "*/"
m = re.search(r"composeA\(\s*const Eigen::Matrix<double,9,4> & EE,\s*Eigen::Matrix<double,10,20> & A\)\s*\n\{\n(.*)\n\}\s*$", text, re.S)
body = m.group(1)
body = re.sub(r"\bEE\((\d+),(\d+)\)", r"EE(\1,\2)", body)
body = re.sub(r"\bA\((\d+),(\d+)\)", r"AA(\1,\2)", body)
res = [license_, "",
       "/* Generated by tools/gen_okvis_stewenius.py from the OpenGV fivept_stewenius module (BSD-3-Clause, see",
       " * okvis_port/LICENSES/opengv-BSD-3-Clause.txt); do not edit. EE = 9 x 4 and AA = 10 x 20, both column-major. */",
       '#include "ok_opengv.h"', "#define EE(i,j) (ee[(i) + 9 * (j)])", "#define AA(i,j) (a[(i) + 10 * (j)])", "",
       "void ok_og_stewenius_compose_a(const double* ee, double* a)", "{", body, "}", ""]
OUT.write_text("\n".join(res))
print("wrote", OUT)
